apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  {{ with .Values.constraints }}
    {{ toYaml . | nindent 2 }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          containers:
            - name: {{ .Release.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              {{- if .Values.vars }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- end }}
              command:
                - {{ .Values.shell }}
                - -c
                - {{ .Values.command | quote }}
              envFrom:
                {{- if .Values.vars }}
                - configMapRef:
                    name: {{ .Release.Name }}
                {{- end }}
                {{- if .Values.secret.enabled }}
                - secretRef:
                    name: {{ .Release.Name }}
                {{- end }}
              {{- include "common.volumeMountsRef.tpl" . | nindent 14 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- include "common.volumesRef.tpl" . | nindent 10 }}
          {{ with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 8 }}
          {{- end }}
          {{ with .Values.affinity }}
          affinity:
            {{ toYaml . | nindent 8 }}
          {{- end }}
          {{ with .Values.tolerations }}
          tolerations:
            {{ toYaml . | nindent 8 }}
          {{- end }}
